sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t chinmaydeshmukh98/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true chinmaydeshmukh98/docker-react npm run test
